import { TILE_SIZE } from '../constants.js';

export class Renderer {
  constructor(canvas, ctx) { this.canvas = canvas; this.ctx = ctx; this.camera = { x:0, y:0, w:canvas.width, h:canvas.height }; this.world={w:canvas.width,h:canvas.height}; this._target={x:0,y:0}; }
  setWorldSize(w,h){ this.world.w=w; this.world.h=h; }
  cameraFollow(target){ // 设定目标位置（含速度前瞻）
    const look = (target.vx||0) * 0.25;
    const cx=target.x + target.w/2 + look - this.canvas.width/2;
    const cy=target.y + target.h/2 - this.canvas.height/2;
    this._target.x = Math.max(0,Math.min(cx,this.world.w-this.canvas.width));
    this._target.y = Math.max(0,Math.min(cy,this.world.h-this.canvas.height));
  }
  updateCamera(dt){ const s=1-Math.pow(0.001, dt*60); // 平滑插值（60fps 基准）
    this.camera.x += (this._target.x - this.camera.x)*s;
    this.camera.y += (this._target.y - this.camera.y)*s;
  }
  clear(){ this.ctx.clearRect(0,0,this.canvas.width,this.canvas.height); }
  drawBackground(level){ const ctx=this.ctx; const theme = (level?.theme) || (level?.activeRoom==='sub' ? 'underground' : 'sky');
    if (theme === 'castle') { const g=ctx.createLinearGradient(0,0,0,this.canvas.height); g.addColorStop(0,'#1f2937'); g.addColorStop(1,'#111827'); ctx.fillStyle=g; ctx.fillRect(0,0,this.canvas.width,this.canvas.height); }
    else if (theme === 'underground') { const g=ctx.createLinearGradient(0,0,0,this.canvas.height); g.addColorStop(0,'#0ea5e9'); g.addColorStop(1,'#0369a1'); ctx.fillStyle=g; ctx.fillRect(0,0,this.canvas.width,this.canvas.height); }
    else { /* sky */ }
    if (theme === 'sky') { ctx.save(); ctx.translate(-this.camera.x*0.2,-this.camera.y*0.2); ctx.fillStyle='#ffffff80'; for(let i=0;i<6;i++){ const x=200+i*300; const y=100+(i%3)*40; this.#cloud(x,y);} ctx.restore(); ctx.save(); ctx.translate(-this.camera.x*0.4,-this.camera.y*0.1); ctx.fillStyle='#7fbf5b'; for(let i=0;i<8;i++){ const x=100+i*400; const y=this.canvas.height-80; this.#hill(x,y);} ctx.restore(); }
  }
  drawLevel(level){ const ctx=this.ctx; const c=this.camera; const startCol=Math.floor(c.x/TILE_SIZE); const endCol=Math.min(level.cols-1,Math.floor((c.x+c.w)/TILE_SIZE)); const startRow=Math.floor(c.y/TILE_SIZE); const endRow=Math.min(level.rows-1,Math.floor((c.y+c.h)/TILE_SIZE)); for(let r=startRow;r<=endRow;r++){ for(let col=startCol; col<=endCol; col++){ const t=level.get(col,r); if(t==='-') continue; const x=col*TILE_SIZE-c.x; const y=r*TILE_SIZE-c.y; if(t==='#'||t==='B'||t==='N'){ ctx.fillStyle=t==='#'?'#7c4f1d':'#a16207'; ctx.fillRect(x,y,TILE_SIZE,TILE_SIZE); ctx.strokeStyle='#00000033'; ctx.lineWidth=2; ctx.strokeRect(x+1,y+1,TILE_SIZE-2,TILE_SIZE-2); if(t==='N'){ ctx.fillStyle='#eab30822'; ctx.fillRect(x+6,y+6,TILE_SIZE-12,TILE_SIZE-12);} } else if (t==='F'){ ctx.fillStyle='#14532d'; ctx.fillRect(x+TILE_SIZE*0.45,y-TILE_SIZE*3,4,TILE_SIZE*4); ctx.fillStyle='#16a34a'; ctx.beginPath(); ctx.moveTo(x+TILE_SIZE*0.45+4,y-TILE_SIZE*3); ctx.lineTo(x+TILE_SIZE*0.45+4+24,y-TILE_SIZE*3+12); ctx.lineTo(x+TILE_SIZE*0.45+4,y-TILE_SIZE*3+24); ctx.closePath(); ctx.fill(); } else if (t==='Q'){ ctx.fillStyle='#f59e0b'; ctx.fillRect(x,y,TILE_SIZE,TILE_SIZE); ctx.strokeStyle='#78350f'; ctx.strokeRect(x+1,y+1,TILE_SIZE-2,TILE_SIZE-2); ctx.fillStyle='#78350f'; ctx.font='bold 18px sans-serif'; ctx.fillText('?',x+10,y+22);} else if (t==='V'){ ctx.fillStyle='#16a34a'; ctx.fillRect(x,y,TILE_SIZE,TILE_SIZE); ctx.fillStyle='#15803d'; ctx.fillRect(x,y,TILE_SIZE,8); ctx.fillRect(x+4,y+8,TILE_SIZE-8,TILE_SIZE-8);} else if (t==='X'){ ctx.fillStyle='#15803d'; ctx.fillRect(x,y,TILE_SIZE,TILE_SIZE); ctx.fillStyle='#16a34a'; ctx.fillRect(x+4,y+4,TILE_SIZE-8,TILE_SIZE-8);} } } }
  drawEntity(ent){ const {x,y,w,h}=ent; const sx=Math.floor(x-this.camera.x); const sy=Math.floor(y-this.camera.y); const ctx=this.ctx; if(ent.kind==='player'){ this.#drawPlayer(ctx,sx,sy,w,h,ent);} else if(ent.kind==='enemy'){ ctx.fillStyle='#8b5e34'; ctx.fillRect(sx,sy,w,h); ctx.strokeStyle='#5b3b1e'; ctx.beginPath(); const t=(ent.animTime||0)*10; ctx.moveTo(sx,sy+h*0.7+Math.sin(t)*2); ctx.lineTo(sx+w,sy+h*0.7+Math.sin(t)*2); ctx.stroke(); } else if(ent.kind==='coin'||ent.kind==='reward-coin'){ ctx.fillStyle='#facc15'; ctx.beginPath(); ctx.ellipse(sx+w/2,sy+h/2,w/2,h/2,0,0,Math.PI*2); ctx.fill(); ctx.strokeStyle='#92400e'; ctx.stroke(); } else if(ent.kind==='mushroom'){ ctx.fillStyle='#16a34a'; ctx.beginPath(); ctx.arc(sx+w/2,sy+h*0.55,w*0.55,Math.PI,0); ctx.fill(); ctx.fillStyle='#fef3c7'; ctx.fillRect(sx+w*0.32,sy+h*0.55,w*0.36,h*0.35);} else if(ent.kind==='flower'){ ctx.fillStyle='#ef4444'; ctx.beginPath(); ctx.arc(sx+w/2, sy+h/2, w*0.45, 0, Math.PI*2); ctx.fill(); ctx.fillStyle='#16a34a'; ctx.fillRect(sx+w*0.45, sy+h*0.55, w*0.1, h*0.4);}  else if(ent.kind==='star'){ ctx.fillStyle='#fcd34d'; ctx.beginPath(); for(let i=0;i<5;i++){ const a=(i*72-90)*Math.PI/180; const r=w/2; const px=sx+w/2+Math.cos(a)*r; const py=sy+h/2+Math.sin(a)*r; if(i===0) ctx.moveTo(px,py); else ctx.lineTo(px,py); const a2=a+36*Math.PI/180; const r2=r*0.5; ctx.lineTo(sx+w/2+Math.cos(a2)*r2, sy+h/2+Math.sin(a2)*r2);} ctx.closePath(); ctx.fill(); } else if(ent.kind==='piranha'){ ctx.fillStyle='#059669'; ctx.fillRect(sx, sy, w, h); ctx.fillStyle='#064e3b'; ctx.fillRect(sx+4, sy+h-6, w-8, 4); ctx.fillStyle='#ecfeff'; ctx.fillRect(sx+3, sy+4, w-6, 6);} else if(ent.kind==='bullet'{ ctx.fillStyle='#fb923c'; ctx.beginPath(); ctx.arc(sx+w/2,sy+h/2,w/2,0,Math.PI*2); ctx.fill(); ctx.fillStyle='#7c2d12'; ctx.fillRect(sx+w*0.2, sy+h*0.45, w*0.6, 2);} else if(ent.kind==='koopa'||ent.kind==='shell'){ ctx.fillStyle=ent.kind==='shell'?'#16a34a':'#047857'; ctx.fillRect(sx,sy,w,h); ctx.fillStyle='#064e3b'; ctx.fillRect(sx+2, sy+h-6, w-4, 4);} else if(ent.kind==='firebar'){ const balls=ent.balls(TILE_SIZE); ctx.fillStyle='#f97316'; for(const b of balls){ const bx=Math.floor(b.cx-this.camera.x), by=Math.floor(b.cy-this.camera.y); ctx.beginPath(); ctx.arc(bx,by,b.radius,0,Math.PI*2); ctx.fill(); } } }
  #cloud(x,y){ const ctx=this.ctx; ctx.beginPath(); ctx.arc(x,y,18,0,Math.PI*2); ctx.arc(x+18,y+6,16,0,Math.PI*2); ctx.arc(x+36,y,20,0,Math.PI*2); ctx.fill(); }
  #hill(x,y){ const ctx=this.ctx; ctx.beginPath(); ctx.moveTo(x-60,y); ctx.lineTo(x,y-80); ctx.lineTo(x+80,y); ctx.closePath(); ctx.fill(); }
  #drawPlayer(ctx,sx,sy,w,h,ent){ const t=ent.animTime||0; const headH=h*0.35; const bodyH=h-headH; ctx.fillStyle='#dc2626'; ctx.fillRect(sx+2, sy+headH, w-4, bodyH-4); ctx.fillStyle='#f1c27d'; ctx.fillRect(sx+4, sy+2, w-8, headH-2); ctx.fillStyle='#b91c1c'; ctx.fillRect(sx+2, sy+0, w-4, headH*0.45); ctx.fillStyle='#1f2937'; const eyeX = ent.facing>=0 ? sx+w*0.65 : sx+w*0.3; ctx.fillRect(eyeX, sy+headH*0.45, 3, 4); ctx.fillStyle='#2563eb'; ctx.fillRect(sx+w*0.28, sy+headH+2, 4, bodyH-6); ctx.fillRect(sx+w*0.68, sy+headH+2, 4, bodyH-6); ctx.fillStyle='#facc15'; ctx.fillRect(sx+w*0.28, sy+headH+bodyH*0.45, 3, 3); ctx.fillRect(sx+w*0.68, sy+headH+bodyH*0.45, 3, 3); ctx.fillStyle='#1f2937'; if(!ent.grounded){ ctx.fillRect(sx+5, sy+h-10, w*0.35, 4); ctx.fillRect(sx+w-5-w*0.35, sy+h-10, w*0.35, 4);} else { const run=Math.min(1, Math.abs(ent.vx||0)/(ent.maxSpeed||200)); const swing=Math.sin(t*20)*3*run; ctx.fillRect(sx+4+swing, sy+h-6, w*0.35, 4); ctx.fillRect(sx+w-4-w*0.35-swing, sy+h-6, w*0.35, 4);} if(ent.invincibleTime&&ent.invincibleTime>0){ ctx.fillStyle='rgba(252,211,77,0.4)'; ctx.fillRect(sx-2,sy-2,w+4,h+4);} }
}
